apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-bmncmh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/mbasti-test-org/jvm-build-cncl-tenant/jvm-build-suite-application-sicy/jvm-build-suite-component-bmncmh@sha256:af7af710f6c063b0b729c279dcbe24d3e1d2a32e3eaa55cc70aa0c2c87a3916b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
