apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-bmncmh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-bmncmh
    app.kubernetes.io/part-of: jvm-build-suite-application-sicy
  name: jvm-build-suite-component-bmncmh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-bmncmh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-bmncmh
    spec:
      containers:
      - image: quay.io/mbasti-test-org/jvm-build-cncl-tenant/jvm-build-suite-application-sicy/jvm-build-suite-component-bmncmh@sha256:af7af710f6c063b0b729c279dcbe24d3e1d2a32e3eaa55cc70aa0c2c87a3916b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
